version: "3.1"
services:
  api:
    build:
      context: .
    ports:
      - 8080:8080
  postgres:
    image: postgres:latest
    container_name: postgresql_example
    environment:
      POSTGRES_DB: example_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "27852:5432"
    restart: unless-stopped
volumes:
  pg-data:
